create table if not exists public.system_f_log
(
    id                         bigint generated by default as identity
        constraint pk_system_f_log
            primary key,
    user_id                    varchar,
    user_login                 varchar,
    http_method                varchar,
    url                        varchar,
    action                     varchar,
    action_domain              varchar,
    request_data_change        varchar,
    response_data_after_change varchar,
    action_status              varchar,
    response_status            varchar,
    dt_create                  timestamp,
    base_exception             varchar,
    stack_trace_on_error       varchar
);

alter table public.system_f_log
    owner to test;